backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


media_folder: 'static/images'

collections:
  - name: "news"
    label: "News"
    folder: "content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}